acrolinx/sdk-js

- src/check.ts
- test/integration-server/acrolinx-endpoint.test.ts
Support added for XIncluisions XML element
Added a test case
> DEV-28790 Support XInclusion References 

- src/check.ts
- test/integration-server/acrolinx-endpoint.test.ts
Updated request-id to requestId
> DEV-31193; fix: Update requestId in live request

- src/index.ts
- src/signin-device-grant.ts
- test/integration-server/acrolinx-one-endpoint.test.ts
- Add provision for additional headers
- Provide helper function `isDeviceAuthResponse`
> DEV-37486; fix: add provision for additional headers

- src/index.ts
- test/integration-server/acrolinx-one-endpoint.test.ts
Part of https://acrolinx.atlassian.net/browse/OPP-562
See also https://acrolinx.slack.com/archives/C06GK8SR03G/p1709727241346589 and
> OPP-562; feat: getAiFeatures

- package-lock.json
- package.json
- src/index.ts
Refactor: Type naming convention
Deps: Update some deps
> refactor: update dependencies, use interface naming convention

- src/ai-service.ts
- src/common-types.ts
- src/headers.ts
- src/index.ts
- src/signin.ts
- src/utils/fetch.ts
Refactor: Index file
- Move independent functions to separate modules
- Untangle fetch logic from endpoint
- provide service type for Acrolinx One Vs Acrolinx Core services
No change to SDK API
> DEV-37860; refactor: move fetch and sign-in to appropriate files

- package-lock.json
- package.json
- test/test-utils/common-mocking.ts
> Update to typescript v5

- src/ai-service.ts
- src/errors.ts
- test/integration-server/acrolinx-one-endpoint.test.ts
- test/unit/ai-service.test.ts
> DEV-37860; fix: add error handling for AI service

- src/errors.ts
- src/index.ts
- src/services/ai-service/ai-service.ts
- src/services/ai-service/ai-service.types.ts
- src/services/ai-service/ai-service.utils.ts
- test/integration-server/acrolinx-one-endpoint.test.ts
- test/unit/ai-service.test.ts
Move AI service to its seprate module
- Introduces services directory
- Move AI service to a separate module
- refactor code to adjust the changes
Service dir structure
|--src
|--/services
|----/ai-service
> DEV-37860; refactor: move ai service to a separate module

- package-lock.json
- package.json
- src/errors.ts
- src/services/ai-service/ai-service.types.ts
- src/services/ai-service/ai-service.utils.ts
- test/unit/ai-service.test.ts
We need the **ENUM error list** from backend team to be added into sdk-js,
> DEV-37127; feat: add new contract for error handling ai-service

- package-lock.json
- package.json
- src/index.ts
- src/services/ai-service/ai-service.utils.ts
- src/utils/logging-buffer.ts
- test/integration-server/acrolinx-one-endpoint.test.ts
- test/unit/logging-buffer.test.ts
The endpoint serves as central place for everything, so should the logging be configured there.
I have tried to write some code to make the logger accessible. 
-
> feat: make logbuffer accessible to endpoint

- .github/workflows/main.yml
- package-lock.json
- package.json
Documentation deployment fix.
Upload correctly to gh-pages branch
> fix: github pages deployment

- jest.config.js
- package-lock.json
- package.json
- tsconfig.json
> build: bump to ES6

- src/errors.ts
- src/services/ai-service/ai-service.types.ts
- src/services/ai-service/ai-service.utils.ts
- test/unit/ai-service.test.ts
> fix: error types with ai service

- .github/workflows/main.yml
- eslint.config.js
- package-lock.json
- package.json
- src/errors.ts
- src/index.ts
- tsconfig.json
- Add ESlint rule for properly handling promises
- Fix improperly handled promises
> chore: validate promises

- package-lock.json
- package.json
- src/services/ai-service/ai-service.ts
- test/unit/ai-service.test.ts
> DEV-39053: fix: move query parms to body

- README.md
- package-lock.json
- package.json
- release v1.3.2
- update readme badges
> chore: release v1.3.2

- package-lock.json
- package.json
- Correct dist path and remove invalid src dir from it
> fix: dist path

- package-lock.json
- package.json
- tsconfig.json
- Compile tests
- Skip lib check (node_mudules)
-
> Fix dir resolutions

- test/integration-server/acrolinx-endpoint.test.ts
- Remove explicit timeouts, rely on global timeouts
> chore: remove explicit timeouts, rely on global test timeouts

- eslint.config.js
- package-lock.json
- package.json
- test/integration-server/acrolinx-endpoint.test.ts
- test/integration-server/acrolinx-one-endpoint.test.ts
- tsconfig.json
- vitest.config.ts
- Fix tests for multi tenant
- Remove redundant sonar plugin from eslint (Sonar cloud does the job)
> chore: fix tests

- .prettierignore
- package-lock.json
- package.json
- src/telemetry/acrolinxInstrumentation.ts
- test/unit/telemetry/telemetry-init.test.ts
Add unit tests with fetch mocking for telemetry
> DEV-42366; test: mock fetch calls

- .changeset/every-pillows-share.md
- .changeset/honest-lies-cross.md
- .changeset/pre.json
- .changeset/swift-sides-reply.md
- CHANGELOG.md
- package-lock.json
- package.json
> NONE chore: bump major version

- .changeset/pre.json
- .changeset/six-stars-open.md
- CHANGELOG.md
- package-lock.json
- package.json
- src/services/ai-service/ai-service.ts
- src/services/int-service/int-service.ts
- fix relative imports
- remove async from non-awaitable functions
> NONE fix: relative import paths

- .changeset/pre.json
- .changeset/silly-tools-cheat.md
- CHANGELOG.md
- package-lock.json
- package.json
- src/telemetry/acrolinxInstrumentation.ts
fix imports in telemetry files
> NONE chore: fix imports in telemetry files

- .changeset/itchy-jars-own.md
- .changeset/pre.json
- CHANGELOG.md
- package-lock.json
- package.json
- src/index.ts
This reverts commit e0efaebdd15c5ba84f6622f05ee3d34224045c37.
> NONE revert "chore: remove interface exports"

- .changeset/evil-oranges-obey.md
- .changeset/pre.json
- CHANGELOG.md
- package-lock.json
- package.json
- src/telemetry/metrics/attribute-utils.ts
- src/telemetry/metrics/metric-constants.ts
- src/telemetry/metrics/metrics-setup.ts
- test/unit/telemetry/telemtry-attribute.test.ts
> DEV-42367 chore: update metric attributes

- .changeset/fruity-women-sip.md
- .changeset/pre.json
- CHANGELOG.md
- package-lock.json
- package.json
- src/index.ts
- src/telemetry/metrics/metric-constants.ts
- src/telemetry/metrics/metrics-setup.ts
- Use appropriate units. See https://opentelemetry.io/docs/specs/otel/metrics/api/
- fix use of correct instrument in check call
> DEV-42366 fix: use correct metric units
